// Regenerates src/embedded-glyph-font.ts: a Bravura subset containing only the
// SMuFL glyphs the renderer draws, base64-encoded so the display package can
// inject it as an @font-face at runtime with zero setup for consumers.
//
// Run via `make generate-glyph-font` whenever the set of glyphs the renderer
// emits changes. The generated file is committed, so normal installs and builds
// never need `subset-font` or @fontsource/bravura at runtime.
import { readFileSync, writeFileSync } from "node:fs";
import subsetFont from "subset-font";
import { RENDERED_GLYPH_CODEPOINTS } from "../src/glyphs";

// The exact SMuFL codepoints the renderer can emit, sorted for stable output.
const GLYPH_CODEPOINTS: number[] = [...RENDERED_GLYPH_CODEPOINTS].sort(
  (a, b) => a - b,
);

const FONT_FAMILY = "BravuraEmbedded";

const sourcePath = require.resolve(
  "@fontsource/bravura/files/bravura-latin-400-normal.woff2",
);
const source = readFileSync(sourcePath);

const text = GLYPH_CODEPOINTS.map((cp) => String.fromCodePoint(cp)).join("");
const subset = await subsetFont(source, text, { targetFormat: "woff2" });
const base64 = subset.toString("base64");

const outputPath = `${import.meta.dir}/../src/embedded-glyph-font.ts`;
const codepointLiterals = GLYPH_CODEPOINTS.map(
  (cp) => `0x${cp.toString(16)}`,
).join(", ");

const contents = `// GENERATED by scripts/generate-glyph-font.ts — do not edit by hand.
// A Bravura subset (only the SMuFL glyphs the renderer draws), base64-encoded
// woff2. Run \`make generate-glyph-font\` to regenerate.

/** Font-family name the bundled subset is registered under. Namespaced so it
 *  cannot collide with a consumer page's own "Bravura" @font-face. */
export const GLYPH_FONT_FAMILY = ${JSON.stringify(FONT_FAMILY)};

/** Codepoints present in the embedded subset — used by the drift-guard test. */
export const EMBEDDED_GLYPH_CODEPOINTS: readonly number[] = [${codepointLiterals}];

/** The Bravura subset as a base64-encoded woff2. */
export const EMBEDDED_GLYPH_FONT_BASE64 =
  ${JSON.stringify(base64)};
`;

writeFileSync(outputPath, contents);
console.log(
  `Wrote ${outputPath} (${GLYPH_CODEPOINTS.length} glyphs, ${subset.length} bytes woff2, ${base64.length} bytes base64)`,
);
